---
notifications:
  email: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"

before_install:
- npm install -g npm

install:
- npm install
- ./node_modules/.bin/lerna bootstrap
script:
- npm run exec-test
- npm run lint
- npm run test

after_success: npm run coverage
