---
notifications:
  email: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"
install:
- npm install
- ./node_modules/.bin/lerna bootstrap
script:
- npm run exec-test
- npm run lint
- npm run test
after_success:
- bash <(curl -s https://codecov.io/bash)
